# Generated by Django 6.0 on 2026-03-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
