# Generated by Django 6.0 on 2026-03-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalcourt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courts/'),
        ),
    ]
