# Generated by Django 6.0 on 2026-03-30 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_futsalcourt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courts/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='futsal.futsalcourt')),
            ],
        ),
    ]
