# Generated by Django 6.0 on 2026-03-31 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_futsalcourt_amenities_timeslot_price_weeklybooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('prize_pool', models.CharField(max_length=100)),
                ('entry_fee', models.CharField(max_length=100)),
                ('team_limit', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rules', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('status', models.CharField(choices=[('Registration Open', 'Registration Open'), ('Registration Closed', 'Registration Closed'), ('Completed', 'Completed')], default='Registration Open', max_length=50)),
                ('state', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('history', 'History')], default='upcoming', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('player_names', models.JSONField(default=list)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='futsal.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
