# Generated by Django 6.0 on 2026-04-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0009_booking_customer_name_booking_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tournament_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='futsal.tournamentregistration'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='futsal.booking'),
        ),
    ]
